### ISSUE TITLE
Auto alimentation

### ISSUE THREAD

**Issue by cosygarcia** [hallard/Denky-D4#1]
Bonjour Charles,
Félicitation pour cette belle réalisation qu'est le Denky D4.
Dans le cas d’un compteur Linky à l’extérieur de la maison comment faudrait-il faire pour utiliser la borne A du Linky pour alimenter le Denky D4 ?
Merci d’avance

**Comment by hallard** [comment]
Bonjour,
C'est en cours avec Jérôme on travaille sur une nouvelle version :-)
https://gricad-gitlab.univ-grenoble-alpes.fr/ferrarij/winky
