### ISSUE TITLE
Compat avec ESPHome

### ISSUE THREAD

**Issue by alucryd** [hallard/Denky-D4#2]
Bonjour,

Je viens juste de commander un D4, il semble que le bug suivant pourrait être gênant si je flashe ESPHome dessus: https://github.com/esphome/issues/issues/4151

Je peux répliquer dans l'éditeur, par contre si je sélectionne `adafruit_qtpy_esp32` comme board je n'ai plus d'erreur. Est-ce que ça a déja pu être testé, histoire que je ne fasse pas n'importe quoi ?

**Comment by hallard** [comment]
Bonjour oui je crois que la reponse est dans l'issue originale.

Sinon qq info ici et la  https://forum.hacf.fr/t/separer-les-heures-creuses-et-pleines-en-fonction-d-un-sensor/20164/17
