### ISSUE TITLE
Missing sensors in HA

### ISSUE THREAD

**Issue by jsapede** [hallard/Denky-D4#5]
Hello,

installed this weekend denky D4 and seems to work well with homeassistant.

Howevoer, in HA i got some sensors always to Zero : 

![linky 2024-01-22 074704](https://github.com/hallard/Denky-D4/assets/66303110/9618d59d-aef7-4504-9ab7-cb6f7af2f351)

looks like power is correctly upstreramed, an i build my own energy counters but what to do with those zero counters  ? is it normal ? its there a manipulation to do on the linky ?

Jimmy

**Comment by hallard** [comment]
@jsapede sorry about delay, for home assistant you can use excellent firmware done by Nicolas, Home Assistant integration is native as others.
check this out https://github.com/NicolasBernaerts/tasmota/tree/master/teleinfo
