### ISSUE TITLE
compatibility with Linky?

### ISSUE THREAD

**Issue by Abdull** [hallard/Denky-D4#7]
Dear Charles,

sorry if noob question (smart meters are implemented differently in Germany):

* is the Denky D4 compatible with French Linky boxes?
* if so, how would the be connected to a Linky box? Via connecting cables to the Linky box (when taking of its green cover) at its lower right corner? Could you provide example photos?
* Using a Teleinfo-enabled Tasmota firmware, is the Denky-D4 already self-sufficient for reporting current and historical data ,e.g. by visiting its own web interface? Or does it require a further separate home automation application, e.g. a dedicated Home Assistant installation, which connects to the Denky-D4 and pulls data?

Thanks in advance

**Comment by hallard** [comment]
Hi @Abdull 

>is the Denky D4 compatible with French Linky boxes?

yes fully compatible, 

> if so, how would the be connected to a Linky box?

for pin it needs to be connected to pins I1 and I2 pins, no matter what sense it's not polarized. they are located under green cover (bottom right) but sometimes at other places see [here](https://www.google.com/search?sca_esv=ad3cebe3ffb4734a&sca_upv=1&rlz=1C5CHFA_enFR944FR944&sxsrf=ADLYWIJ2nB5MONtNBylsM-kUBkNKvsRE8A:1724104332898&q=connecter+le+linky+i1+i2&udm=2&fbs=AEQNm0CbCVgAZ5mWEJDg6aoPVcBgWJkeaSBjnexh07HhnqtPCNlhAfWp8uCcnPq9-h5RrlH39iBZX9QIiLWgwUZh7C5yAlNEJW-aePHcBqBL96rOaC3Vf4bSn2O04AB7SNn0BopY2kwMSQ5Ebdv3AVUrp6QQuHoMJAUcFHFN9Gc2qc1B5axILIBRlZBDgphgC_SF8CuQ3QnE&sa=X&ved=2ahUKEwj3u8WShYKIAxXoU6QEHSc6DhQQtKgLegQIGBAB&biw=2129&bih=1147&dpr=1)

> Using a Teleinfo-enabled Tasmota firmware, is the Denky-D4 already self-sufficient for reporting current and historical data

I suggest using latest Nicolas firmware, rocks and have some onboard graphics history if you don't want to use a separate home automation system.
https://github.com/NicolasBernaerts/tasmota/tree/master/teleinfo
